var anyNumber = 19;
console.log("Is anyNumber == '19'? I predict True.");
console.log(anyNumber == 19);
console.log("Is anyNumber% 19=='0'? I predict True.");
console.log(anyNumber % 19 == 0);
console.log("Is anyNumber/ 2 == '9.5'? I predict True.");
console.log(anyNumber / 2 == 9.5);
console.log("Is anyNumber - 4 == '15'? I predict True.");
console.log(anyNumber - 4 == 15);
console.log("Is anyNumber + 1 == '20'? I predict True.");
console.log(anyNumber + 1 == 20);
console.log("Is anyNumber == '19'? I predict True.");
console.log(anyNumber > 19);
console.log("Is anyNumber% 19=='0'? I predict True.");
console.log(anyNumber % 19 < 0);
console.log("Is anyNumber/ 2 == '9.5'? I predict True.");
console.log(anyNumber / 2 > 9.5);
console.log("Is anyNumber - 4 == '15'? I predict True.");
console.log(anyNumber - 4 == 16 || anyNumber - 4 == 14);
console.log("Is anyNumber + 1 == '20'? I predict True.");
console.log(anyNumber + 1 != 20);
//################################### Question 24 ###################################
console.log(typeof anyNumber === 'number');
console.log(typeof anyNumber === 'string');
